export const moments = ["calm", "working", "attention", "recovery"] as const;
export type Moment = (typeof moments)[number];
export type RuntimeState = "idle" | "working" | "waiting" | "blocked" | "done" | "unknown";
export type ChangeKind = "new" | "changed" | "finished" | "stale" | "recovered" | "none";
export type GoalLifecycle = "active" | "completed" | "archived";

export interface GoalFixture {
  readonly id: string;
  readonly title: string;
  readonly priority: "P0" | "P1" | "P2";
  readonly description: string;
  readonly colour: string;
  readonly glow: string;
  readonly position: readonly [number, number, number];
  readonly radius: number;
  readonly lifecycle?: GoalLifecycle;
  readonly changed?: boolean;
}

export interface AgentFixture {
  readonly id: string;
  readonly name: string;
  readonly role: string;
  readonly goalId?: string;
  readonly colour: string;
  readonly orbit: number;
  readonly phase: number;
  readonly speed: number;
  readonly states: Readonly<Record<Moment, RuntimeState>>;
  readonly repository: string;
  readonly branch: string;
  readonly activity: string;
  readonly attention?: string;
  readonly parentId?: string;
  readonly recentChange?: ChangeKind;
  readonly observedMinutesAgo?: number;
}

export const goals: readonly GoalFixture[] = [
  {
    id: "observatory",
    title: "Understand Concurrent Agent Work",
    priority: "P0",
    description:
      "Make concurrent agent work understandable without holding its shape in your head.",
    colour: "#645cff",
    glow: "#9b8cff",
    position: [-7.4, 0.1, 0],
    radius: 2.25,
  },
  {
    id: "frontier",
    title: "Ship a Truthful Frontier Alpha",
    priority: "P1",
    description: "Build a truthful, legible AI company simulation worthy of a wider alpha.",
    colour: "#ed6e43",
    glow: "#ffb45f",
    position: [-2.1, -0.8, -1],
    radius: 1.9,
  },
  {
    id: "mason",
    title: "Keep Humans in Control of Agent Execution",
    priority: "P2",
    description: "Keep the human in control while agents gain useful execution power.",
    colour: "#16a78b",
    glow: "#66e6bf",
    position: [3.0, 0.4, -2],
    radius: 1.7,
  },
  {
    id: "hearth",
    title: "Automate Weekly Family Food Planning",
    priority: "P1",
    description: "Remove the weekly planning burden from feeding a busy family well.",
    colour: "#d4528f",
    glow: "#ff9fc7",
    position: [8.2, -0.5, -1],
    radius: 1.5,
  },
  {
    id: "signals",
    title: "Find the Right AI-First Product Role",
    priority: "P2",
    description: "Find unusually strong AI product opportunities without creating noise.",
    colour: "#448de8",
    glow: "#8ac4ff",
    position: [-8.2, -5.4, -2],
    radius: 1.45,
  },
  {
    id: "launchpad",
    title: "Validate a New Product Direction",
    priority: "P2",
    description: "Turn promising technical ideas into small, decisive product experiments.",
    colour: "#8a5de8",
    glow: "#c6a4ff",
    position: [-3.4, -5.8, -2],
    radius: 1.55,
  },
  {
    id: "extensions",
    title: "Establish Safe Extension Boundaries",
    priority: "P1",
    description: "Let useful extensions participate without bypassing policy or audit.",
    colour: "#9d704f",
    glow: "#c5966f",
    position: [1.9, -5.0, -1],
    radius: 1.45,
    changed: true,
  },
  {
    id: "release",
    title: "Prepare the September Product Release",
    priority: "P0",
    description: "Bring the release through evidence, communication and production verification.",
    colour: "#6f8b75",
    glow: "#9cbaa3",
    position: [7.6, -5.7, 0],
    radius: 1.65,
    changed: true,
  },
  {
    id: "evaluation",
    title: "Prove the Agent Harness Is Dependable",
    priority: "P1",
    description: "Measure the simple tool loop before adding coordination machinery.",
    colour: "#777c9d",
    glow: "#a5abc8",
    position: [-7.9, 5.8, -1],
    radius: 1.5,
  },
  {
    id: "research",
    title: "Map the Next Generation of AI Tooling",
    priority: "P2",
    description: "Turn a noisy technology landscape into a small set of grounded decisions.",
    colour: "#a08372",
    glow: "#c7a996",
    position: [-2.9, 5.3, -2],
    radius: 1.4,
  },
  {
    id: "handoff",
    title: "Close the Architecture Review Findings",
    priority: "P2",
    description: "Carry accepted design findings into the durable architecture and implementation plan.",
    colour: "#7f927b",
    glow: "#a8baa2",
    position: [2.4, 6.0, -2],
    radius: 1.45,
    lifecycle: "completed",
  },
  {
    id: "archive",
    title: "Retire the Rejected Renderer Experiments",
    priority: "P2",
    description: "Preserve the renderer verdict while removing abandoned implementations from active work.",
    colour: "#8d8478",
    glow: "#aaa095",
    position: [7.7, 5.2, -3],
    radius: 1.35,
    lifecycle: "archived",
  },
];

const steady = (state: RuntimeState): Readonly<Record<Moment, RuntimeState>> => ({
  calm: state,
  working: state,
  attention: state,
  recovery: state,
});

const coreAgents: readonly AgentFixture[] = [
  {
    id: "atlas",
    name: "Atlas",
    role: "Interaction lead",
    goalId: "observatory",
    colour: "#e6ddff",
    orbit: 4.1,
    phase: 0.2,
    speed: 0.055,
    states: { calm: "idle", working: "working", attention: "working", recovery: "working" },
    repository: "ao",
    branch: "main",
    activity: "Shaping the web observatory prototype",
    recentChange: "new",
  },
  {
    id: "lumen",
    name: "Lumen",
    role: "Visual systems",
    goalId: "observatory",
    colour: "#9ed8ff",
    orbit: 4.8,
    phase: 1.15,
    speed: 0.044,
    states: { calm: "idle", working: "working", attention: "blocked", recovery: "working" },
    repository: "ao",
    branch: "prototype/magical-web",
    activity: "Testing shader language and identity",
    attention: "Choose whether goal identity comes from material or silhouette",
    parentId: "atlas",
    recentChange: "changed",
  },
  {
    id: "kepler",
    name: "Kepler",
    role: "Projection review",
    goalId: "observatory",
    colour: "#f1baff",
    orbit: 5.35,
    phase: 2.1,
    speed: 0.036,
    states: { calm: "idle", working: "working", attention: "waiting", recovery: "done" },
    repository: "ao",
    branch: "main",
    activity: "Projection parity review complete",
    attention: "Review returned projection findings",
    parentId: "atlas",
    recentChange: "finished",
  },
  {
    id: "umbra",
    name: "Umbra",
    role: "Failure-state research",
    goalId: "observatory",
    colour: "#f2dfb6",
    orbit: 5.9,
    phase: 3.2,
    speed: 0.028,
    states: { calm: "idle", working: "unknown", attention: "unknown", recovery: "idle" },
    repository: "ao",
    branch: "research/host-loss",
    activity: "Host observation is stale",
    recentChange: "stale",
    observedMinutesAgo: 24,
  },
  {
    id: "relay",
    name: "Relay",
    role: "Host integration",
    goalId: "observatory",
    colour: "#7ef2db",
    orbit: 4.45,
    phase: 4.1,
    speed: 0.05,
    states: steady("working"),
    repository: "ao",
    branch: "main",
    activity: "Validating mock host transitions",
  },
  {
    id: "scribe",
    name: "Scribe",
    role: "Product narrative",
    goalId: "observatory",
    colour: "#ffd9b8",
    orbit: 5.1,
    phase: 5.2,
    speed: 0.03,
    states: { calm: "idle", working: "working", attention: "done", recovery: "done" },
    repository: "ao",
    branch: "main",
    activity: "POC specification captured",
  },
  {
    id: "meridian",
    name: "Meridian",
    role: "Accessibility",
    goalId: "observatory",
    colour: "#f6f2ff",
    orbit: 6.2,
    phase: 5.8,
    speed: 0.024,
    states: steady("idle"),
    repository: "ao",
    branch: "main",
    activity: "Reduced-motion encoding queued",
  },
  {
    id: "forge",
    name: "Forge",
    role: "Economy systems",
    goalId: "frontier",
    colour: "#ffd076",
    orbit: 3.5,
    phase: 0.5,
    speed: 0.052,
    states: steady("working"),
    repository: "frontier",
    branch: "main",
    activity: "Running funding scenarios",
  },
  {
    id: "quill",
    name: "Quill",
    role: "Narrative design",
    goalId: "frontier",
    colour: "#ff9a72",
    orbit: 4.1,
    phase: 1.65,
    speed: 0.041,
    states: { calm: "idle", working: "working", attention: "working", recovery: "working" },
    repository: "frontier",
    branch: "main",
    activity: "Rewriting board feedback",
  },
  {
    id: "rook",
    name: "Rook",
    role: "Balance reviewer",
    goalId: "frontier",
    colour: "#ffe7c4",
    orbit: 4.7,
    phase: 2.8,
    speed: 0.035,
    states: { calm: "idle", working: "working", attention: "blocked", recovery: "idle" },
    repository: "frontier",
    branch: "review/balance",
    activity: "Scenario review needs a decision",
    attention: "Choose whether late-stage hiring is intentionally constrained",
  },
  {
    id: "ember",
    name: "Ember",
    role: "Visual design",
    goalId: "frontier",
    colour: "#ff764d",
    orbit: 3.9,
    phase: 4.0,
    speed: 0.048,
    states: steady("working"),
    repository: "frontier",
    branch: "art/campus",
    activity: "Producing research icon set",
  },
  {
    id: "delta",
    name: "Delta",
    role: "Regression analysis",
    goalId: "frontier",
    colour: "#ffcfa6",
    orbit: 4.45,
    phase: 5.15,
    speed: 0.03,
    states: { calm: "idle", working: "working", attention: "done", recovery: "done" },
    repository: "frontier",
    branch: "main",
    activity: "All curated scenarios green",
    recentChange: "finished",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    role: "Runtime policy",
    goalId: "mason",
    colour: "#79f2cf",
    orbit: 3.2,
    phase: 0.8,
    speed: 0.052,
    states: steady("working"),
    repository: "agent-repl",
    branch: "main",
    activity: "Checking extension authority seams",
  },
  {
    id: "mosaic",
    name: "Mosaic",
    role: "Provider adapter",
    goalId: "mason",
    colour: "#93d8ff",
    orbit: 3.8,
    phase: 2.1,
    speed: 0.044,
    states: { calm: "idle", working: "working", attention: "working", recovery: "working" },
    repository: "agent-repl",
    branch: "pi-foundation",
    activity: "Normalising provider events",
  },
  {
    id: "axiom",
    name: "Axiom",
    role: "Security review",
    goalId: "mason",
    colour: "#d8fff2",
    orbit: 4.3,
    phase: 3.5,
    speed: 0.033,
    states: { calm: "idle", working: "working", attention: "waiting", recovery: "done" },
    repository: "agent-repl",
    branch: "review/extensions",
    activity: "Transactional activation review returned",
    attention: "Accept or revise the extension trust boundary",
    recentChange: "changed",
  },
  {
    id: "thread",
    name: "Thread",
    role: "Evaluation",
    goalId: "mason",
    colour: "#afffd9",
    orbit: 3.55,
    phase: 5.0,
    speed: 0.04,
    states: { calm: "idle", working: "unknown", attention: "unknown", recovery: "idle" },
    repository: "agent-repl",
    branch: "evals",
    activity: "Last observation 18 minutes ago",
    recentChange: "stale",
    observedMinutesAgo: 18,
  },
  {
    id: "pantry",
    name: "Pantry",
    role: "Basket planning",
    goalId: "hearth",
    colour: "#ffacd0",
    orbit: 3.2,
    phase: 0.4,
    speed: 0.043,
    states: steady("working"),
    repository: "family-food-agent",
    branch: "main",
    activity: "Reconciling the weekly basket",
  },
  {
    id: "saffron",
    name: "Saffron",
    role: "Meal planning",
    goalId: "hearth",
    colour: "#ffd08b",
    orbit: 3.8,
    phase: 2.0,
    speed: 0.037,
    states: { calm: "idle", working: "working", attention: "waiting", recovery: "done" },
    repository: "family-food-agent",
    branch: "plans/weekly",
    activity: "Weekly plan ready for approval",
    attention: "Approve the substitutions for two unavailable ingredients",
    recentChange: "changed",
  },
  {
    id: "tally",
    name: "Tally",
    role: "Price comparison",
    goalId: "hearth",
    colour: "#f3b8ff",
    orbit: 4.2,
    phase: 4.2,
    speed: 0.031,
    states: steady("working"),
    repository: "family-food-agent",
    branch: "retailer-comparison",
    activity: "Comparing retailer totals",
  },
  {
    id: "radar",
    name: "Radar",
    role: "Opportunity research",
    goalId: "signals",
    colour: "#93caff",
    orbit: 3.2,
    phase: 0.8,
    speed: 0.046,
    states: steady("working"),
    repository: "career-notes",
    branch: "research/ai-product",
    activity: "Scanning AI platform roles",
  },
  {
    id: "prism",
    name: "Prism",
    role: "Role analysis",
    goalId: "signals",
    colour: "#b5dcff",
    orbit: 3.8,
    phase: 2.8,
    speed: 0.034,
    states: steady("idle"),
    repository: "career-notes",
    branch: "main",
    activity: "Comparing ownership and commute constraints",
  },
  {
    id: "beacon",
    name: "Beacon",
    role: "Outreach",
    goalId: "signals",
    colour: "#d6eeff",
    orbit: 4.2,
    phase: 5.1,
    speed: 0.028,
    states: { calm: "idle", working: "idle", attention: "unknown", recovery: "idle" },
    repository: "career-notes",
    branch: "outreach",
    activity: "Last observation 31 minutes ago",
    recentChange: "stale",
    observedMinutesAgo: 31,
  },
  {
    id: "spark",
    name: "Spark",
    role: "Product discovery",
    goalId: "launchpad",
    colour: "#d5baff",
    orbit: 3.1,
    phase: 0.2,
    speed: 0.048,
    states: steady("working"),
    repository: "product-studio",
    branch: "main",
    activity: "Testing the smallest useful proposition",
  },
  {
    id: "kiln",
    name: "Kiln",
    role: "Prototype engineer",
    goalId: "launchpad",
    colour: "#f0b5ff",
    orbit: 3.7,
    phase: 1.9,
    speed: 0.041,
    states: steady("working"),
    repository: "product-studio",
    branch: "poc/control-surface",
    activity: "Building a disposable interaction proof",
    parentId: "spark",
  },
  {
    id: "verdict",
    name: "Verdict",
    role: "Experiment analysis",
    goalId: "launchpad",
    colour: "#c9c3ff",
    orbit: 4.2,
    phase: 3.7,
    speed: 0.032,
    states: steady("done"),
    repository: "product-studio",
    branch: "main",
    activity: "Renderer experiment captured",
    parentId: "spark",
    recentChange: "finished",
  },
  {
    id: "harbor",
    name: "Harbor",
    role: "Risk review",
    goalId: "launchpad",
    colour: "#a9d9ff",
    orbit: 4.7,
    phase: 5.4,
    speed: 0.027,
    states: steady("idle"),
    repository: "product-studio",
    branch: "main",
    activity: "Waiting for the next experiment",
  },
  {
    id: "drift",
    name: "Drift",
    role: "Unassigned research",
    colour: "#88a5c9",
    orbit: 2.1,
    phase: 0.5,
    speed: 0.025,
    states: steady("idle"),
    repository: "unknown",
    branch: "—",
    activity: "Awaiting a Goal",
  },
  {
    id: "echo",
    name: "Echo",
    role: "Unassigned review",
    colour: "#a58ed4",
    orbit: 2.8,
    phase: 2.4,
    speed: 0.032,
    states: steady("idle"),
    repository: "ao",
    branch: "scratch/review",
    activity: "Awaiting a Goal",
  },
  {
    id: "wander",
    name: "Wander",
    role: "Unassigned spike",
    colour: "#7890a8",
    orbit: 3.4,
    phase: 4.6,
    speed: 0.02,
    states: steady("unknown"),
    repository: "unknown",
    branch: "—",
    activity: "No recent host observation",
  },
  {
    id: "pioneer",
    name: "Pioneer",
    role: "Unassigned implementation",
    colour: "#9fb8d2",
    orbit: 3.7,
    phase: 5.5,
    speed: 0.036,
    states: steady("working"),
    repository: "ao",
    branch: "scratch/pioneer",
    activity: "Working without accepted Goal",
  },
];

const generatedNames = [
  "Northstar",
  "Trace",
  "Cairn",
  "Gauge",
  "Plumb",
  "Anvil",
  "Ledger",
  "Margin",
  "Vellum",
  "Current",
  "Compass",
  "Grove",
  "Larder",
  "Thimble",
  "Index",
  "Facet",
  "Contour",
  "Trestle",
  "Warden",
  "Latch",
  "Bastion",
  "Accord",
  "Sentry",
  "Cadence",
  "Proof",
  "Measure",
  "Caliper",
  "Testbed",
  "Query",
  "Survey",
  "Archive",
  "Folio",
  "Context",
  "Bridge",
  "Mortar",
  "Span",
  "Rivet",
  "Seal",
  "Parcel",
  "Receipt",
  "Chisel",
  "Whetstone",
  "Platen",
  "Patina",
  "Waymark",
] as const;

const generatedGoalIds = [
  "observatory",
  "observatory",
  "observatory",
  "frontier",
  "frontier",
  "frontier",
  "mason",
  "mason",
  "mason",
  "hearth",
  "hearth",
  "signals",
  "signals",
  "launchpad",
  "launchpad",
  "extensions",
  "extensions",
  "extensions",
  "extensions",
  "extensions",
  "release",
  "release",
  "release",
  "release",
  "release",
  "evaluation",
  "evaluation",
  "evaluation",
  "evaluation",
  "evaluation",
  "research",
  "research",
  "research",
  "research",
  "research",
  "handoff",
  "handoff",
  "handoff",
  "handoff",
  "handoff",
  "archive",
  "archive",
  "archive",
  "archive",
  "archive",
] as const;

const generatedRoles = [
  "Evidence review",
  "Implementation",
  "Host observation",
  "Product analysis",
  "Quality review",
] as const;

const generatedAgents: readonly AgentFixture[] = generatedNames.map((name, index) => {
  const goalId = generatedGoalIds[index];
  const attention = index % 11 === 0;
  const stale = index % 13 === 0;
  const finished = index % 7 === 0;
  const state: RuntimeState = stale
    ? "unknown"
    : attention
      ? "waiting"
      : finished
        ? "done"
        : index % 3 === 0
          ? "idle"
          : "working";
  const recentChange: ChangeKind = "none";
  return {
    id: `fixture-${index + 1}`,
    name,
    role: generatedRoles[index % generatedRoles.length],
    goalId,
    colour: "#8f8778",
    orbit: 3.2 + (index % 4) * 0.45,
    phase: (index * 1.91) % (Math.PI * 2),
    speed: 0.02 + (index % 5) * 0.006,
    states: {
      calm: finished ? "done" : "idle",
      working: state === "unknown" ? "unknown" : finished ? "done" : "working",
      attention: state,
      recovery: stale ? "idle" : finished ? "done" : "working",
    },
    repository: goalId === "release" ? "release-control" : goalId,
    branch: finished ? "main" : `work/${name.toLowerCase()}`,
    activity: finished
      ? "Result recorded and ready for verification"
      : stale
        ? `Host observation is ${22 + (index % 17)} minutes old`
        : attention
          ? "Waiting for an explicit operator decision"
          : "Advancing the current evidence package",
    attention: attention ? "Choose whether the current evidence is sufficient to proceed" : undefined,
    recentChange,
    observedMinutesAgo: stale ? 22 + (index % 17) : 0,
  };
});

export const agents: readonly AgentFixture[] = [...coreAgents, ...generatedAgents];

export const goalFor = (agent: AgentFixture): GoalFixture | undefined =>
  goals.find((goal) => goal.id === agent.goalId);

export const stateFor = (agent: AgentFixture, moment: Moment): RuntimeState => agent.states[moment];

export const needsAttention = (agent: AgentFixture, moment: Moment): boolean => {
  const state = stateFor(agent, moment);
  return state === "blocked" || state === "waiting";
};
